# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  vmenvs
    resourceType: VirtualMachine
    tags: web
  strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                if [ -d "/home/azureuser/chess" ] 
                then
                    cd /home/azureuser/chess
                    git pull https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git master
                else
                    git clone https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git /home/azureuser/chess
                fi
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                cd /home/azureuser/chess
                export SECRET_KEY=$(SECRET_KEY)
                export POSTGRESQL_USER=$(POSTGRESQL_USER)
                export POSTGRESQL_PASSWORD=$(POSTGRESQL_PASSWORD)
                export POSTGRESQL_DATABASE=$(POSTGRESQL_DATABASE)
                export POSTGRESQL_HOST=$(POSTGRESQL_HOST)
                export POSTGRESQL_PORT=$(POSTGRESQL_PORT)
                sudo docker-compose up -d --build