# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  vmenvs
    resourceType: VirtualMachine
    tags: web
  strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                set -o errexit
                set -o nounset
                
                IFS=$(printf '\n\t')
                
                # Docker
                sudo apt remove --yes docker docker-engine docker.io containerd runc
                sudo apt update
                sudo apt --yes --no-install-recommends install apt-transport-https ca-certificates
                wget --quiet --output-document=- https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release --codename --short) stable"
                sudo apt update
                sudo apt --yes --no-install-recommends install docker-ce docker-ce-cli containerd.io
                sudo usermod --append --groups docker "$USER"
                sudo systemctl enable docker
                printf '\nDocker installed successfully\n\n'
                
                printf 'Waiting for Docker to start...\n\n'
                sleep 5
                
                # Docker Compose
                sudo wget --output-document=/usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/$(wget --quiet --output-document=- https://api.github.com/repos/docker/compose/releases/latest | grep --perl-regexp --only-matching '"tag_name": "\K.*?(?=")')/run.sh"
                sudo chmod +x /usr/local/bin/docker-compose
                sudo wget --output-document=/etc/bash_completion.d/docker-compose "https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose"
                printf '\nDocker Compose installed successfully\n\n'
                
                # git init
                
                if [ -d "/chess" ] 
                then
                    git clone https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git
                else
                    cd chess
                    git pull https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git master
                fi
                
                # Run project
                
                sudo docker-compose up -d --build