# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  vmenvs
    resourceType: VirtualMachine
    tags: web
  strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                set -o errexit
                set -o nounset
                
                if [ -d "/chess" ] 
                then
                    git clone https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git /chess
                else
                    cd /chess
                    git pull https://$(USER):$(TOKEN)@github.com/ChessStankin/chess.git master
                fi
                