version: "3.8"
   
services:
  web:
    container_name: django_app
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: variables.env
    ports:
     - "8000:8000"
    command: python3.9 src/chess/manage.py runserver 0.0.0.0:8000
