# Generated by Django 3.1.3 on 2020-12-02 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authjwt',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 14, 34, 34, 632081)),
        ),
        migrations.AlterField(
            model_name='authjwt',
            name='token',
            field=models.CharField(default='90eda32a500f71cf4a1e61f5d024247e9802207d04df30f71e95403b5ae54dcc', max_length=64),
        ),
    ]
