# Generated by Django 3.1.3 on 2020-12-02 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201202_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authjwt',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 14, 39, 4, 33)),
        ),
        migrations.AlterField(
            model_name='authjwt',
            name='token',
            field=models.CharField(default='fd303f3b6f40f668eda8a432bc9e440616f85cb4d8698fe79972b65adc675a42', max_length=64),
        ),
    ]
