# Generated by Django 3.1.3 on 2020-12-02 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201202_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authjwt',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 14, 42, 28, 670991)),
        ),
        migrations.AlterField(
            model_name='authjwt',
            name='token',
            field=models.CharField(default='2038500af3f8c405e3b73d1dd364e090820d892fb1c99294c5b2739377a2c4b3', max_length=64),
        ),
    ]
