# Generated by Django 3.1.3 on 2020-12-02 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201202_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authjwt',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 15, 24, 17, 514242)),
        ),
        migrations.AlterField(
            model_name='authjwt',
            name='token',
            field=models.CharField(default='dffc249f34856706a9c92b30e6499b02ad9b8fbef5cb4b07bdec00bcb89c5e8d', max_length=64),
        ),
    ]
